### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by playdasegunda** [jhtonyKoo/e2e_music_remastering_system#2]
Error trying to inference:

```
(mdx-submit) C:\Users\lucas\Downloads\e2e_music_remastering_system>python inference.py --data_dir_test "C:\Users\lucas\Downloads\e2e_music_remastering_system\inference_samples\set_1"
C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
C:\Users\lucas\Downloads\e2e_music_remastering_system\Self_Supervised_Music_Remastering_System\config.py:90: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
---reloaded checkpoint weights - Mastering Cloner---
---reloaded checkpoint weights - Music Effects Encoder---
C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
Traceback (most recent call last):
  File "inference.py", line 159, in <module>
    inf.inference()
  File "inference.py", line 77, in inference
    for step, (whole_song_ori, whole_song_ref, song_name) in enumerate(self.data_loader):
  File "C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\lucas\anaconda3\envs\mdx-submit\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\lucas\Downloads\e2e_music_remastering_system\Self_Supervised_Music_Remastering_System\data_loader\data_loader.py", line 248, in __getitem__
    song_name = cur_aud_path_ori.split('/')[-2]
IndexError: list index out of range


(mdx-submit) C:\Users\lucas\Downloads\e2e_music_remastering_system>
```

* the input.wav and reference.wav file are already in the 'set_1' folder

Torch version: 1.8.1+cu111
GPU: RTX 2060 (6 GB)

What can it be?

**Comment by jhtonyKoo** [comment]
Hey there, the code was implemented in Linux OS, so maybe the solution is to 

1. try changing the line 248 of the file 'data_loader.py': "song_name = cur_aud_path_ori.split('/')[-2]" to "song_name = cur_aud_path_ori.split('\\')[-2]"
2. and change the command line to 
$ python inference.py --data_dir_test "C:\Users\lucas\Downloads\e2e_music_remastering_system\inference_samples\\"

Sorry for the inconvenience.

**Comment by playdasegunda** [comment]
Hi,

I ended up changing the line as suggested,

I used this: `cur_aud_path_ori.split('')[-2]"`

and this: `cur_aud_path_ori.split(' ')[-2]"` with space between the quotes, but still the problem persisted,

As I don't have linux it won't be possible to use,

As many people use Windows they got the same problem, so it would be interesting to refactor the codes for better compatibility for other OS.

1. Do you have any other suggestions on how to solve this problem?
2. I also noticed that it doesn't have a requirements.txt or yaml file it would be interesting to generate too,

Thanks in advance once again.

**Comment by jhtonyKoo** [comment]
I've updated the comment before so the '\\' symbol is now visible... Please try to revise the line again with it.

Thanks for the feedback regarding the compatibility and install requirements. I'll soon refactor the code and add requirements for this repo.

**Comment by playdasegunda** [comment]
I tried using the '\' but got the following error:

```
song_name = cur_aud_path_ori.split('\')
                                          ^
SyntaxError: EOL while scanning string literal
```

The solution I found was this:

replace `cur_aud_path_ori.split('')[-2]"` to `song_name = cur_aud_path_ori.split(' ')`

It creates this directory "inference_samples\('inference_samples\set_1\input.wav',)\inferred_output.wav" with the remastered file, 

I don't know if this would be the right way, but at least what it indicates is that it worked.

Thanks again!
